"""add_status_column_to_events

Revision ID: 59bed5b72b5a
Revises: ec89a2d94b38
Create Date: 2025-11-08 17:51:10.926200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59bed5b72b5a'
down_revision: Union[str, None] = 'ec89a2d94b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('status', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    # 添加 CheckConstraint 確保 status 值為 'upcoming', 'ongoing', 'past' 或 NULL
    op.create_check_constraint(
        'check_status_values',
        'events',
        "status IN ('upcoming', 'ongoing', 'past') OR status IS NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_status_values', 'events', type_='check')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_column('events', 'status')
    # ### end Alembic commands ###

