"""add_user_checkpoint_progress_table

Revision ID: 9c1bc4024828
Revises: ec89a2d94b38
Create Date: 2025-11-08 20:06:36.617283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1bc4024828'
down_revision: Union[str, None] = 'ec89a2d94b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('checkpoint_type', sa.Enum('NFC', 'QUESTION', 'QRCODE', name='checkpointtype'), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('nfc_tag_id', sa.Integer(), nullable=True),
    sa.Column('question_data', sa.Text(), nullable=True),
    sa.Column('qrcode_data', sa.String(length=255), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reward_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nfc_tag_id'], ['nfc_tags.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkpoints_checkpoint_type'), 'checkpoints', ['checkpoint_type'], unique=False)
    op.create_index(op.f('ix_checkpoints_id'), 'checkpoints', ['id'], unique=False)
    op.create_index(op.f('ix_checkpoints_mission_id'), 'checkpoints', ['mission_id'], unique=False)
    op.create_index(op.f('ix_checkpoints_name'), 'checkpoints', ['name'], unique=False)
    op.create_index(op.f('ix_checkpoints_nfc_tag_id'), 'checkpoints', ['nfc_tag_id'], unique=False)
    op.create_index(op.f('ix_checkpoints_order'), 'checkpoints', ['order'], unique=False)
    op.create_table('user_checkpoint_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('checkpoint_id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_data', sa.Text(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['checkpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_checkpoint_progress_checkpoint_id'), 'user_checkpoint_progress', ['checkpoint_id'], unique=False)
    op.create_index(op.f('ix_user_checkpoint_progress_id'), 'user_checkpoint_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_checkpoint_progress_user_id'), 'user_checkpoint_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_checkpoint_progress_user_id'), table_name='user_checkpoint_progress')
    op.drop_index(op.f('ix_user_checkpoint_progress_id'), table_name='user_checkpoint_progress')
    op.drop_index(op.f('ix_user_checkpoint_progress_checkpoint_id'), table_name='user_checkpoint_progress')
    op.drop_table('user_checkpoint_progress')
    op.drop_index(op.f('ix_checkpoints_order'), table_name='checkpoints')
    op.drop_index(op.f('ix_checkpoints_nfc_tag_id'), table_name='checkpoints')
    op.drop_index(op.f('ix_checkpoints_name'), table_name='checkpoints')
    op.drop_index(op.f('ix_checkpoints_mission_id'), table_name='checkpoints')
    op.drop_index(op.f('ix_checkpoints_id'), table_name='checkpoints')
    op.drop_index(op.f('ix_checkpoints_checkpoint_type'), table_name='checkpoints')
    op.drop_table('checkpoints')
    # ### end Alembic commands ###

