"""Add Mission model and update NFC_Tag relationship

Revision ID: ec89a2d94b38
Revises: fa6235876955
Create Date: 2025-11-08 11:56:18.777303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec89a2d94b38'
down_revision: Union[str, None] = 'fa6235876955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_event_id'), 'missions', ['event_id'], unique=False)
    op.create_index(op.f('ix_missions_id'), 'missions', ['id'], unique=False)
    op.create_index(op.f('ix_missions_name'), 'missions', ['name'], unique=False)
    op.create_index(op.f('ix_missions_order'), 'missions', ['order'], unique=False)
    
    # 先添加 mission_id 為可空，以便遷移現有資料
    op.add_column('nfc_tags', sa.Column('mission_id', sa.Integer(), nullable=True))
    
    # 如果有現有的 nfc_tags 資料，為每個創建對應的 mission
    # 注意：這假設 checkpoint_name 可以用作 mission name
    connection = op.get_bind()
    
    # 檢查是否有現有資料
    count_result = connection.execute(sa.text("SELECT COUNT(*) FROM nfc_tags"))
    nfc_count = count_result.scalar()
    
    if nfc_count > 0:
        # 為每個現有的 nfc_tag 創建對應的 mission
        result = connection.execute(sa.text("""
            SELECT id, event_id, checkpoint_name, scan_order 
            FROM nfc_tags 
            WHERE event_id IS NOT NULL
        """))
        
        for row in result:
            nfc_id, event_id, checkpoint_name, scan_order = row
            mission_name = checkpoint_name if checkpoint_name else f'Mission {scan_order or 0}'
            
            # 創建 mission
            mission_insert = sa.text("""
                INSERT INTO missions (event_id, name, description, "order", is_active, created_at, updated_at)
                VALUES (:event_id, :name, :description, :order, true, now(), now())
                RETURNING id
            """)
            mission_result = connection.execute(mission_insert, {
                'event_id': event_id,
                'name': mission_name,
                'description': f'Mission for {checkpoint_name or mission_name}',
                'order': scan_order if scan_order is not None else 0
            })
            mission_id = mission_result.scalar()
            
            # 更新對應的 nfc_tag
            update_stmt = sa.text("""
                UPDATE nfc_tags 
                SET mission_id = :mission_id 
                WHERE id = :nfc_id
            """)
            connection.execute(update_stmt, {
                'mission_id': mission_id,
                'nfc_id': nfc_id
            })
    
    # 現在將 mission_id 設為不可空
    op.alter_column('nfc_tags', 'mission_id', nullable=False)
    
    op.drop_index(op.f('ix_nfc_tags_event_id'), table_name='nfc_tags')
    op.drop_constraint(op.f('uq_event_checkpoint'), 'nfc_tags', type_='unique')
    op.create_index(op.f('ix_nfc_tags_mission_id'), 'nfc_tags', ['mission_id'], unique=True)
    op.drop_constraint(op.f('nfc_tags_event_id_fkey'), 'nfc_tags', type_='foreignkey')
    op.create_foreign_key(None, 'nfc_tags', 'missions', ['mission_id'], ['id'], ondelete='CASCADE')
    op.drop_column('nfc_tags', 'checkpoint_name')
    op.drop_column('nfc_tags', 'scan_order')
    op.drop_column('nfc_tags', 'event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nfc_tags', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('nfc_tags', sa.Column('scan_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('nfc_tags', sa.Column('checkpoint_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'nfc_tags', type_='foreignkey')
    op.create_foreign_key(op.f('nfc_tags_event_id_fkey'), 'nfc_tags', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_nfc_tags_mission_id'), table_name='nfc_tags')
    op.create_unique_constraint(op.f('uq_event_checkpoint'), 'nfc_tags', ['event_id', 'checkpoint_name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_nfc_tags_event_id'), 'nfc_tags', ['event_id'], unique=False)
    op.drop_column('nfc_tags', 'mission_id')
    op.drop_index(op.f('ix_missions_order'), table_name='missions')
    op.drop_index(op.f('ix_missions_name'), table_name='missions')
    op.drop_index(op.f('ix_missions_id'), table_name='missions')
    op.drop_index(op.f('ix_missions_event_id'), table_name='missions')
    op.drop_table('missions')
    # ### end Alembic commands ###

